name: 'Config Translation PO'
type: module
description: 'Configuration Translations to PO file'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'configuration'

dependencies:
  - drupal:locale
  - drupal:config_translation

# Information added by Drupal.org packaging script on 2020-08-25
version: '1.0.x-dev'
project: 'config_translation_po'
datestamp: 1598360613
