workflow.type_settings.workflows_field:
  type: mapping
  label: 'Workflows Field'
  mapping:
    initial_state:
      type: string
      label: 'Initial state'
    states:
      type: sequence
      sequence:
        type: workflows.state
    transitions:
      type: sequence
      sequence:
        type: workflows.transition

field.storage_settings.workflows_field_item:
  type: mapping
  label: 'Workflows Field Item Storage Settings Schema'
  mapping:
    workflow:
      type: string
      label: 'Workflow'

field.formatter.settings.workflows_field_state_list:
  type: mapping
  label: 'State list settings'
  mapping:
    excluded_states:
      type: sequence
      label: 'A list of excluded states'
      sequence:
        type: string
        label: 'The excluded state'
