field.field_settings.country:
  label: 'Country settings'
  type: mapping
  mapping:
    selectable_countries:
      type: sequence
      label: 'Selectable countries'
      sequence:
        type: string

field.storage_settings.country:
  label: 'Country settings'
  type: mapping
  mapping:
    selectable_countries:
      type: sequence
      label: 'Selectable countries'
      sequence:
        type: string

views.filter.country_item:
  type: views_filter
  label: 'Country filter'

views.filter_value.country_item:
  type: mapping
  label: 'Country filter value'
  mapping:
    type:
      type: string
      label: 'Type'