name: Build and push docker image

on:
  push:
    branches: [ main, CmstNewVersion2 ]
  pull_request:
    branches: [ main, CmstNewVersion2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: check out code
      uses: actions/checkout@v2

    - 
      name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: uncfwcarot4d/digitalcms-webapp
        labels: |
          org.opencontainers.image.title=Polyglot CMS
          org.opencontainers.image.description=Content Management System to easily translate digital education courses in humanitarian and community health context
          org.opencontainers.image.vendor=UNICEF WCARO / T4D
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

    - 
      name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }} # if event is push (alternative to : `push: true`)
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}