name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
        local: testedb.sql
        remote: /home/dev/web/drupal-dev-lms.wcar-t4d.info/public_html
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}