on: 
  pull_request:
    branches:
      - main
  
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploying cmst translation
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      env:
        DB_NAME: ${{ DB_NAME }}
        DB_USER: ${{ DB_USER }}
        DB_PASSWORD: ${{ DB_PASSWORD }}
        
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: /home/dev/web/drupal-dev-lms.wcar-t4d.info/public_html
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}